server:
  port:                     8210
  servlet:
    context-path: /gateway

spring:
  application:
      name:                                               spring-gateway
  cloud:
    gateway:
      routes:
      - id: personnes-service
        uri: http://localhost:9010
        predicates:
        - Path=/personnes/**
        - Weight=per1, 90
        filters:
          - StripPrefix=1

      - id: personnes-service-v2
        uri: http://localhost:9012
        predicates:
        - Path=/personnes/**
        - Weight=per1, 10
        filters:
          - StripPrefix=1

      - id: rentes-service
        uri: http://localhost:9020
        predicates:
        - Path=/rentes/**
        filters:
          - StripPrefix=1

      metrics:
        enabled: true





management:

  endpoint:
    metrics:
      enabled: true

    prometheus:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true

  endpoints:

    web:
      exposure:
        include: "*"
    beans:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/